### ISSUE TITLE
角色重名伤害统计bug

### ISSUE THREAD

**Issue by yjstcb** [SlightQuartz/Idle-Adenture-Plugin#11]
伤害统计，如果3个角色里面有重名的话，会被统计到其中一个上面。

**Comment by Nov31** [comment]
+1

**Comment by AuroraYu** [comment]
同队伍的英雄还能够重名么...  
情况已经了解了，问题应该也能够解决，但因为现在统计是使用的英雄名称，改成按位置统计需要一定时间。等完成现有功能的开发后会来进行修复，请耐心等待。

**Comment by AuroraYu** [comment]
相关bug修复已经完成
