### ISSUE TITLE
这个图好像不对吧。。。

### ISSUE THREAD

**Issue by yjstcb** [SlightQuartz/Idle-Adenture-Plugin#14]
RT

![image](https://user-images.githubusercontent.com/13567673/41526056-90c25c56-7315-11e8-983b-d939f80a678e.png)

**Comment by yjstcb** [comment]
![image](https://user-images.githubusercontent.com/13567673/41526103-af34545a-7315-11e8-8bb3-8862d0b37995.png)

**Comment by yjstcb** [comment]
是不是图的数据来源的名字也因为重了所以乱了。我这是2个角色。

**Comment by SlightQuartz** [comment]
你是不是用了相同的角色名？

**Comment by yjstcb** [comment]
对的，相同角色名

**Comment by SlightQuartz** [comment]
试一下新的，我修了下名称

**Comment by yjstcb** [comment]
没问题了
